-- cycle — full database schema
-- Auto-generated by concatenating supabase/migrations/*.sql in order.
-- Paste this whole file into the Supabase SQL editor and click Run.


-- ======================================================================
-- 20260725031947_0001_profiles_and_auth_trigger.sql
-- ======================================================================
/*
# Create profiles table and auth trigger

1. New Tables
   - `profiles`
     - `id` (uuid, PK, references auth.users on delete cascade)
     - `display_name` (text, nullable)
     - `avatar_url` (text, nullable)
     - `created_at` (timestamptz, default now())

2. Security
   - Enable RLS on `profiles`
   - SELECT policy: authenticated users can read their own profile
   - UPDATE policy: authenticated users can update their own profile
   - INSERT policy: authenticated users can insert their own profile (for trigger)

3. Trigger
   - `handle_new_user()` function (SECURITY DEFINER) auto-creates a profiles row on auth.users insert
   - Trigger fires AFTER INSERT on auth.users

4. Notes
   - Partner-visible SELECT policy will be added in a later migration once `pairings` table exists
   - display_name is seeded from auth metadata if available
*/

-- Profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  avatar_url text,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Policies (drop first for idempotency)
DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own" ON profiles FOR SELECT
  TO authenticated USING (id = auth.uid());

DROP POLICY IF EXISTS "profiles_update_own" ON profiles;
CREATE POLICY "profiles_update_own" ON profiles FOR UPDATE
  TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());

DROP POLICY IF EXISTS "profiles_insert_own" ON profiles;
CREATE POLICY "profiles_insert_own" ON profiles FOR INSERT
  TO authenticated WITH CHECK (id = auth.uid());

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'display_name', NULL));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ======================================================================
-- 20260725032005_0002_pairings_and_are_paired.sql
-- ======================================================================
/*
# Create pairings table and are_paired() helper

1. New Types
   - `pairing_status` enum: 'pending', 'active', 'unsynced'

2. New Tables
   - `pairings`
     - `id` (uuid, PK)
     - `code` (text, unique, not null) - single-use join code
     - `user_a` (uuid, not null, FK profiles) - creator
     - `user_b` (uuid, nullable, FK profiles) - joiner (null until joined)
     - `status` (pairing_status, default 'pending')
     - `created_at`, `activated_at`, `ended_at` (timestamptz)

3. Functions
   - `are_paired(u1 uuid, u2 uuid)` - returns true if two users share an active pairing

4. Security
   - RLS enabled on `pairings`
   - SELECT: members can see their own pairings
   - INSERT: authenticated user can create (must be user_a)
   - UPDATE: members can update their pairing (for joining/unsyncing)

5. Updated Policies
   - `profiles` SELECT policy updated to allow partner visibility via are_paired()

6. Notes
   - "One active pairing per user" enforced at app layer + partial unique indexes
*/

-- Pairing status enum
DO $$ BEGIN
  CREATE TYPE pairing_status AS ENUM ('pending', 'active', 'unsynced');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Pairings table
CREATE TABLE IF NOT EXISTS pairings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text UNIQUE NOT NULL,
  user_a uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  user_b uuid REFERENCES profiles(id) ON DELETE CASCADE,
  status pairing_status NOT NULL DEFAULT 'pending',
  created_at timestamptz DEFAULT now(),
  activated_at timestamptz,
  ended_at timestamptz
);

-- Partial unique indexes to enforce one active pairing per user
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_pairing_a
  ON pairings (user_a) WHERE status = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_pairing_b
  ON pairings (user_b) WHERE status = 'active';

-- Enable RLS
ALTER TABLE pairings ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "pairings_select_member" ON pairings;
CREATE POLICY "pairings_select_member" ON pairings FOR SELECT
  TO authenticated USING (user_a = auth.uid() OR user_b = auth.uid());

DROP POLICY IF EXISTS "pairings_insert_creator" ON pairings;
CREATE POLICY "pairings_insert_creator" ON pairings FOR INSERT
  TO authenticated WITH CHECK (user_a = auth.uid());

DROP POLICY IF EXISTS "pairings_update_member" ON pairings;
CREATE POLICY "pairings_update_member" ON pairings FOR UPDATE
  TO authenticated USING (user_a = auth.uid() OR user_b = auth.uid());

-- Helper function: are two users in an active pairing?
CREATE OR REPLACE FUNCTION are_paired(u1 uuid, u2 uuid)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM pairings
    WHERE status = 'active'
      AND ((user_a = u1 AND user_b = u2) OR (user_a = u2 AND user_b = u1))
  );
$$;

-- Update profiles SELECT policy to include partner visibility
DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own_or_partner" ON profiles FOR SELECT
  TO authenticated USING (id = auth.uid() OR are_paired(auth.uid(), id));


-- ======================================================================
-- 20260725032027_0003_cycles_logs_sharing.sql
-- ======================================================================
/*
# Create cycles, cycle_logs, and sharing_settings tables

1. New Tables
   - `cycles` - one current cycle record per user
     - `id` (uuid, PK)
     - `user_id` (uuid, FK profiles, not null, default auth.uid())
     - `last_period_start` (date, not null)
     - `avg_cycle_length` (int, default 28)
     - `avg_period_length` (int, default 5)
     - `updated_at` (timestamptz, default now())
   - `cycle_logs` - optional daily tracking
     - `id` (uuid, PK)
     - `user_id` (uuid, FK profiles, not null, default auth.uid())
     - `log_date` (date, not null)
     - `flow` (text) - light/medium/heavy
     - `mood` (text)
     - `symptoms` (jsonb)
     - `note` (text)
     - `created_at` (timestamptz)
   - `sharing_settings` - consent-first: what the tracking partner shares
     - `user_id` (uuid, PK, FK profiles)
     - `share_phase` (boolean, default true)
     - `share_symptoms` (boolean, default false)
     - `share_mood` (boolean, default false)

2. Security
   - RLS on all tables
   - cycles/cycle_logs: self read/write + partner read (via are_paired)
   - sharing_settings: self only (all CRUD)

3. Notes
   - Partner can see cycle data rows (RLS), but app layer gates symptoms/mood by sharing_settings
*/

-- Cycles table
CREATE TABLE IF NOT EXISTS cycles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  last_period_start date NOT NULL,
  avg_cycle_length int NOT NULL DEFAULT 28,
  avg_period_length int NOT NULL DEFAULT 5,
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE cycles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cycles_select_self_or_partner" ON cycles;
CREATE POLICY "cycles_select_self_or_partner" ON cycles FOR SELECT
  TO authenticated USING (user_id = auth.uid() OR are_paired(auth.uid(), user_id));

DROP POLICY IF EXISTS "cycles_insert_self" ON cycles;
CREATE POLICY "cycles_insert_self" ON cycles FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "cycles_update_self" ON cycles;
CREATE POLICY "cycles_update_self" ON cycles FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "cycles_delete_self" ON cycles;
CREATE POLICY "cycles_delete_self" ON cycles FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- Cycle logs table
CREATE TABLE IF NOT EXISTS cycle_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  log_date date NOT NULL,
  flow text,
  mood text,
  symptoms jsonb,
  note text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE cycle_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "logs_select_self_or_partner" ON cycle_logs;
CREATE POLICY "logs_select_self_or_partner" ON cycle_logs FOR SELECT
  TO authenticated USING (user_id = auth.uid() OR are_paired(auth.uid(), user_id));

DROP POLICY IF EXISTS "logs_insert_self" ON cycle_logs;
CREATE POLICY "logs_insert_self" ON cycle_logs FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "logs_update_self" ON cycle_logs;
CREATE POLICY "logs_update_self" ON cycle_logs FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "logs_delete_self" ON cycle_logs;
CREATE POLICY "logs_delete_self" ON cycle_logs FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- Sharing settings table
CREATE TABLE IF NOT EXISTS sharing_settings (
  user_id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  share_phase boolean DEFAULT true,
  share_symptoms boolean DEFAULT false,
  share_mood boolean DEFAULT false
);

ALTER TABLE sharing_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "sharing_select_self" ON sharing_settings;
CREATE POLICY "sharing_select_self" ON sharing_settings FOR SELECT
  TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "sharing_insert_self" ON sharing_settings;
CREATE POLICY "sharing_insert_self" ON sharing_settings FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "sharing_update_self" ON sharing_settings;
CREATE POLICY "sharing_update_self" ON sharing_settings FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "sharing_delete_self" ON sharing_settings;
CREATE POLICY "sharing_delete_self" ON sharing_settings FOR DELETE
  TO authenticated USING (user_id = auth.uid());


-- ======================================================================
-- 20260725032048_0004_messages_nudges_prefs.sql
-- ======================================================================
/*
# Create messages, nudges, and notification_prefs tables

1. New Tables
   - `messages` - persistent chat thread per pairing
     - `id` (uuid, PK)
     - `pairing_id` (uuid, FK pairings, not null)
     - `sender_id` (uuid, FK profiles, not null, default auth.uid())
     - `body` (text, not null)
     - `created_at` (timestamptz, default now())
   - `nudges` - pushed cute notifications
     - `id` (uuid, PK)
     - `pairing_id` (uuid, FK pairings, not null)
     - `sender_id` (uuid, FK profiles, not null, default auth.uid())
     - `kind` (text, default 'custom') - 'preset' or 'custom'
     - `preset_key` (text, nullable)
     - `body` (text, not null)
     - `read_at` (timestamptz, nullable)
     - `created_at` (timestamptz, default now())
   - `notification_prefs` - per-user notification preferences
     - `user_id` (uuid, PK, FK profiles)
     - `email_on_unsync` (boolean, default false)
     - `push_enabled` (boolean, default true)

2. Security
   - RLS on all tables
   - messages/nudges: only members of the pairing can read/send
   - notification_prefs: self only

3. Indexes
   - messages: index on (pairing_id, created_at) for chat loading
   - nudges: index on (pairing_id, created_at) for notification feed

4. Realtime
   - Enable realtime on messages and nudges tables
*/

-- Messages table
CREATE TABLE IF NOT EXISTS messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_id uuid NOT NULL REFERENCES pairings(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  body text NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_messages_pairing_time ON messages (pairing_id, created_at);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "messages_select_member" ON messages;
CREATE POLICY "messages_select_member" ON messages FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM pairings p WHERE p.id = pairing_id
      AND (p.user_a = auth.uid() OR p.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "messages_insert_member" ON messages;
CREATE POLICY "messages_insert_member" ON messages FOR INSERT
  TO authenticated WITH CHECK (
    sender_id = auth.uid() AND EXISTS (
      SELECT 1 FROM pairings p WHERE p.id = pairing_id AND p.status = 'active'
      AND (p.user_a = auth.uid() OR p.user_b = auth.uid())
    )
  );

-- Nudges table
CREATE TABLE IF NOT EXISTS nudges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  pairing_id uuid NOT NULL REFERENCES pairings(id) ON DELETE CASCADE,
  sender_id uuid NOT NULL DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  kind text NOT NULL DEFAULT 'custom',
  preset_key text,
  body text NOT NULL,
  read_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nudges_pairing_time ON nudges (pairing_id, created_at);

ALTER TABLE nudges ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "nudges_select_member" ON nudges;
CREATE POLICY "nudges_select_member" ON nudges FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM pairings p WHERE p.id = pairing_id
      AND (p.user_a = auth.uid() OR p.user_b = auth.uid()))
  );

DROP POLICY IF EXISTS "nudges_insert_member" ON nudges;
CREATE POLICY "nudges_insert_member" ON nudges FOR INSERT
  TO authenticated WITH CHECK (
    sender_id = auth.uid() AND EXISTS (
      SELECT 1 FROM pairings p WHERE p.id = pairing_id AND p.status = 'active'
      AND (p.user_a = auth.uid() OR p.user_b = auth.uid())
    )
  );

DROP POLICY IF EXISTS "nudges_update_member" ON nudges;
CREATE POLICY "nudges_update_member" ON nudges FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM pairings p WHERE p.id = pairing_id
      AND (p.user_a = auth.uid() OR p.user_b = auth.uid()))
  );

-- Notification preferences table
CREATE TABLE IF NOT EXISTS notification_prefs (
  user_id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES profiles(id) ON DELETE CASCADE,
  email_on_unsync boolean DEFAULT false,
  push_enabled boolean DEFAULT true
);

ALTER TABLE notification_prefs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "prefs_select_self" ON notification_prefs;
CREATE POLICY "prefs_select_self" ON notification_prefs FOR SELECT
  TO authenticated USING (user_id = auth.uid());

DROP POLICY IF EXISTS "prefs_insert_self" ON notification_prefs;
CREATE POLICY "prefs_insert_self" ON notification_prefs FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "prefs_update_self" ON notification_prefs;
CREATE POLICY "prefs_update_self" ON notification_prefs FOR UPDATE
  TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "prefs_delete_self" ON notification_prefs;
CREATE POLICY "prefs_delete_self" ON notification_prefs FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- Enable realtime for messages and nudges (guarded so this file is re-runnable)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'messages') THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE messages';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'nudges') THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE nudges';
  END IF;
END $$;


-- ======================================================================
-- 20260725032722_0005_pairings_join_policy.sql
-- ======================================================================
/*
# Add pairing join policy

1. Security Changes
   - Add SELECT policy on `pairings` that allows any authenticated user to see pending pairings
     where user_b is null (so they can look up a code to join)
   - This is safe because: the code is a single-use secret shared intentionally,
     and the row only exposes the pairing ID + code + status (no sensitive data)

2. Notes
   - Without this, Bob can't find Alice's pending pairing to join it
   - The existing member SELECT policy stays for viewing active pairings
*/

DROP POLICY IF EXISTS "pairings_lookup_pending" ON pairings;
CREATE POLICY "pairings_lookup_pending" ON pairings FOR SELECT
  TO authenticated USING (status = 'pending' AND user_b IS NULL);


-- ======================================================================
-- 20260725032756_0006_fix_pairings_update_for_join.sql
-- ======================================================================
/*
# Fix pairings update policy for join flow

1. Security Changes
   - Update the pairings UPDATE policy to also allow any authenticated user to update
     a pending pairing where user_b IS NULL (the join case)
   - The existing member check stays for active pairings (e.g. unsyncing)

2. Notes
   - Without this fix, Bob can't join Alice's pairing because the UPDATE policy
     checks user_a or user_b, but Bob is neither until the update completes
   - The WITH CHECK ensures the updater sets themselves as user_b
*/

DROP POLICY IF EXISTS "pairings_update_member" ON pairings;
CREATE POLICY "pairings_update_member" ON pairings FOR UPDATE
  TO authenticated USING (
    user_a = auth.uid() OR user_b = auth.uid()
    OR (status = 'pending' AND user_b IS NULL)
  )
  WITH CHECK (
    user_a = auth.uid() OR user_b = auth.uid()
  );


-- ======================================================================
-- 20260725035645_0007_add_role_and_weather_to_profiles.sql
-- ======================================================================
/*
# Add role column to profiles + weather column

1. Modified Tables
   - `profiles`
     - Add `role` (text, nullable) — values: 'tracker', 'supporter', 'both', or null (not yet onboarded)
     - Add `weather` (text, nullable) — today's self-set weather icon for the dashboard

2. Notes
   - role determines what UI surfaces the user sees (cycle input vs support-only)
   - weather is the "how are you today?" quick-set on the dashboard
   - No policy changes needed since profiles already has self-select/update policies
*/

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS weather text;


-- ======================================================================
-- 20260725042249_0008_onboarding_steps_and_chat_requests.sql
-- ======================================================================
/*
# Onboarding step machine + chat requests

1. Modified Tables
   - `profiles`
     - Add `onboarding_step` (integer, default 1) — tracks current onboarding step (1-7)
     - Add `onboarding_complete` (boolean, default false) — gates access to main app
   - `messages`
     - Add `type` (text, default 'text') — 'text' or 'request'
     - Add `request_status` (text, nullable) — 'open', 'accepted', 'done'
     - Add `request_category` (text, nullable) — 'feed-me', 'spoil-me', 'errand', 'favor'

2. Notes
   - onboarding_step persists mid-flow so refresh resumes correctly
   - onboarding_complete gates routing: true = go to Home, false = resume onboarding
   - messages.type distinguishes chat requests from normal text
   - request_status tracks the lifecycle: open → accepted → done
*/

ALTER TABLE profiles ADD COLUMN IF NOT EXISTS onboarding_step integer NOT NULL DEFAULT 1;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS onboarding_complete boolean NOT NULL DEFAULT false;

ALTER TABLE messages ADD COLUMN IF NOT EXISTS type text NOT NULL DEFAULT 'text';
ALTER TABLE messages ADD COLUMN IF NOT EXISTS request_status text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS request_category text;


-- ======================================================================
-- 20260725043554_0009_wallets_and_gifts.sql
-- ======================================================================
/*
# Create wallets and gifts tables

1. New Tables
   - `wallets`
     - `id` (uuid, primary key)
     - `user_id` (uuid, unique, FK to auth.users, defaults to auth.uid())
     - `balance` (integer, default 500) — dummy credits in cents
     - `updated_at` (timestamptz)
   - `gifts`
     - `id` (uuid, primary key)
     - `sender_id` (uuid, FK to auth.users, defaults to auth.uid())
     - `recipient_id` (uuid, FK to auth.users)
     - `pairing_id` (uuid, FK to pairings)
     - `name` (text) — gift name e.g. "chocolates"
     - `emoji` (text) — display emoji
     - `cost` (integer) — cost in credits
     - `phase_context` (text, nullable) — which phase triggered this suggestion
     - `status` (text, default 'delivered') — always delivered in dummy mode
     - `created_at` (timestamptz)

2. Security
   - RLS enabled on both tables
   - wallets: users can read/update their own wallet
   - gifts: users can see gifts they sent or received, can insert as sender

3. Notes
   - Every user starts with 500 credits (like a dummy balance)
   - Sending a gift deducts from sender's wallet in the frontend
   - This is a dummy/demo system — no real money involved
*/

CREATE TABLE IF NOT EXISTS wallets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  balance integer NOT NULL DEFAULT 500,
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gifts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  recipient_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  pairing_id uuid REFERENCES pairings(id) ON DELETE SET NULL,
  name text NOT NULL,
  emoji text NOT NULL DEFAULT '🎁',
  cost integer NOT NULL,
  phase_context text,
  status text NOT NULL DEFAULT 'delivered',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE gifts ENABLE ROW LEVEL SECURITY;

-- Wallet policies: own wallet only
DROP POLICY IF EXISTS "select_own_wallet" ON wallets;
CREATE POLICY "select_own_wallet" ON wallets FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_wallet" ON wallets;
CREATE POLICY "insert_own_wallet" ON wallets FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_wallet" ON wallets;
CREATE POLICY "update_own_wallet" ON wallets FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_wallet" ON wallets;
CREATE POLICY "delete_own_wallet" ON wallets FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- Gift policies: can see gifts where you're sender or recipient
DROP POLICY IF EXISTS "select_own_gifts" ON gifts;
CREATE POLICY "select_own_gifts" ON gifts FOR SELECT
  TO authenticated USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

DROP POLICY IF EXISTS "insert_own_gifts" ON gifts;
CREATE POLICY "insert_own_gifts" ON gifts FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "update_own_gifts" ON gifts;
CREATE POLICY "update_own_gifts" ON gifts FOR UPDATE
  TO authenticated USING (auth.uid() = sender_id) WITH CHECK (auth.uid() = sender_id);

DROP POLICY IF EXISTS "delete_own_gifts" ON gifts;
CREATE POLICY "delete_own_gifts" ON gifts FOR DELETE
  TO authenticated USING (auth.uid() = sender_id);


-- ======================================================================
-- 20260725044612_0010_custom_gifts_and_board.sql
-- ======================================================================
/*
# Add custom gift support and gift board visibility

1. Modified Tables
   - `gifts`
     - Add `custom_message` (text, nullable) — user-written message for custom gifts
     - Add `is_board_visible` (boolean, default true) — whether the gift shows on recipient's board

2. Notes
   - Custom gifts have name='custom gift' and use custom_message for the content
   - All gifts default to visible on the board (recipient can hide them later)
   - The gift board is a public showcase of received gifts
*/

ALTER TABLE gifts ADD COLUMN IF NOT EXISTS custom_message text;
ALTER TABLE gifts ADD COLUMN IF NOT EXISTS is_board_visible boolean NOT NULL DEFAULT true;


-- ======================================================================
-- 20260725045313_0011_media_messages_and_stickers.sql
-- ======================================================================
/*
# Add media messages and custom stickers

1. Modified Tables
   - `messages`
     - Add `media_url` (text, nullable) — URL or base64 data of image/drawing
     - Add `media_type` (text, nullable) — 'image', 'drawing', 'sticker', 'video'

2. New Tables
   - `stickers`
     - `id` (uuid, primary key)
     - `user_id` (uuid, FK to auth.users, defaults to auth.uid())
     - `name` (text) — sticker name
     - `image_data` (text) — base64 PNG data of the sticker/drawing
     - `emoji` (text, nullable) — optional emoji label
     - `created_at` (timestamptz)

3. Security
   - RLS enabled on stickers
   - Users can CRUD their own stickers
   - Stickers are personal to each user (they create their own custom emoji library)

4. Notes
   - Images/drawings stored as base64 data URIs in message media_url
   - Stickers are saved drawings that users can reuse
   - No file storage needed since canvas drawings are small base64 PNGs
*/

ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_url text;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_type text;

CREATE TABLE IF NOT EXISTS stickers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT 'untitled',
  image_data text NOT NULL,
  emoji text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE stickers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_stickers" ON stickers;
CREATE POLICY "select_own_stickers" ON stickers FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_stickers" ON stickers;
CREATE POLICY "insert_own_stickers" ON stickers FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_stickers" ON stickers;
CREATE POLICY "update_own_stickers" ON stickers FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_stickers" ON stickers;
CREATE POLICY "delete_own_stickers" ON stickers FOR DELETE
  TO authenticated USING (auth.uid() = user_id);


-- ======================================================================
-- 20260725050000_0012_sharing_partner_read_and_gift_realtime.sql
-- ======================================================================
/*
# Enforceable privacy + gift realtime

1. sharing_settings
   - The privacy dial (share_phase / share_symptoms / share_mood) is meant to be
     enforced in the app layer, but the app running as the *partner* could not
     read the tracker's sharing_settings — the original SELECT policy was
     self-only. Widen SELECT so a paired partner can read the row, which lets the
     dashboard gate what it shows (phase / mood / symptoms) by the tracker's
     choices. Writes stay self-only.

2. gifts realtime
   - Add `gifts` to the realtime publication so the recipient gets a live pop-up
     notification the moment a gift is sent (messages + nudges were already in
     the publication in migration 0004).

3. Notes
   - Row visibility is still restricted to the two paired users; a partner can
     read the booleans but never anyone else's.
*/

-- Allow a paired partner to READ sharing preferences (writes remain self-only).
DROP POLICY IF EXISTS "sharing_select_self" ON sharing_settings;
DROP POLICY IF EXISTS "sharing_select_self_or_partner" ON sharing_settings;
CREATE POLICY "sharing_select_self_or_partner" ON sharing_settings FOR SELECT
  TO authenticated USING (user_id = auth.uid() OR are_paired(auth.uid(), user_id));

-- Live gift delivery for pop-up notifications.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'gifts'
  ) THEN
    EXECUTE 'ALTER PUBLICATION supabase_realtime ADD TABLE gifts';
  END IF;
END $$;

